# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_category',
            field=models.ImageField(upload_to='.catalog/img'),
        ),
    ]
