# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200629_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=200, verbose_name='Name Product')),
                ('image', models.ImageField(upload_to='.catalog/img')),
            ],
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_product',
        ),
        migrations.DeleteModel(
            name='Web_catalog',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='feature_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
    ]
