# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200629_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category_features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_feature', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_prod', to='catalog.Category'),
        ),
    ]
