# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200629_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='category_features',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
