# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200629_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_category',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
