# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200630_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_category',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
