# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200630_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='lala'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='lala'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_category', to='catalog.Category'),
        ),
    ]
