# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200702_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slug_c',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slug_p',
        ),
    ]
