# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200702_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug_p',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_c',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='lala'),
        ),
    ]
