# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='prod_id'),
        ),
    ]
