# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
