# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 07:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200703_0734'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('all_categories', django.db.models.manager.Manager()),
            ],
        ),
    ]
